import Header from "@/components/Header";
import QueryContext from "@/context/QueryContext";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const mst = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryContext>
      <html lang="en">
        <body className={mst.className}>
          <Header />
          <main>{children}</main>
          <div id="portal" />
        </body>
      </html>
    </QueryContext>
  );
}
